#services:
#  db:
#    image: postgres:latest
#    environment:
#      POSTGRES_DB: events
#      POSTGRES_USER: emt
#      POSTGRES_PASSWORD: emt
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#volumes:
#  pgdata:
#
