services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: accommodations
      POSTGRES_USER: emt
      POSTGRES_PASSWORD: emt
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./views.sql:/docker-entrypoint-initdb.d/views.sql


volumes:
  pgdata:
