CREATE TABLE host
(
    id         BIGINT PRIMARY KEY AUTO_INCREMENT,
    name       VARCHAR(255) NOT NULL,
    surname    VARCHAR(255) NOT NULL,
    country_id BIGINT,
    FOREIGN KEY (country_id) REFERENCES country (id)
);



create table country
(
    id        bigint generated by default as identity
        primary key,
    name      varchar(255),
    continent varchar(255)
);

CREATE TABLE accommodation
(
    id        BIGINT PRIMARY KEY AUTO_INCREMENT,
    name      VARCHAR(255) NOT NULL,
    category  VARCHAR(50)  NOT NULL,
    host_id   BIGINT,
    num_rooms INT,
    is_rented BOOLEAN DEFAULT FALSE
);


create table shop_users
(
    username                   varchar(255)
        primary key,
    password                   varchar(255),
    name                       varchar(255),
    surname                    varchar(255),
    is_account_non_expired     boolean default true,
    is_account_non_locked      boolean default true,
    is_credentials_non_expired boolean default true,
    is_enabled                 boolean default true,
    role                       varchar(50)
);

CREATE TABLE review
(
    id      BIGINT PRIMARY KEY AUTO_INCREMENT,
    comment TEXT,
    rate    INT
);


CREATE TABLE temporary_reservation
(
    id      BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT,
    FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE temporary_reservation_accommodations
(
    accommodation_id         BIGINT,
    temporary_reservation_id BIGINT,
    PRIMARY KEY (accommodation_id, temporary_reservation_id),
    FOREIGN KEY (accommodation_id) REFERENCES accommodation (id) ON DELETE CASCADE,
    FOREIGN KEY (temporary_reservation_id) REFERENCES temporary_reservation (id) ON DELETE CASCADE
);


create index idx_cart_user_status on shopping_cart (user_username, status);
create index idx_user_username_password on shop_users (username, password);
create index idx_user_username on shop_users (username);
create index idx_user_role on shop_users (role);
